version: '3.8'

services:
  tulahack-web-26:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tulahack-web-26
    restart: unless-stopped
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0